finalizando testes
devpass-tech/hereminders-ios pull request #19
Opened 2021-08-19 08:46 UTC by dairan

## What does this PR do

* Implementação da classe CircularImageView
* Implementação dos testes de Snapshoting da classe CircularImageView

[Tarefa no Notion](https://www.notion.so/devpass/Implementar-CircularImageView-usando-ViewCode-9ada7a99f4f14924b066ea78cc192d69)

## Any background context you want to provide

* Aproveitei e fiz a implementação do `convenience init` para o entendimento do mesmo e levantar a discursão até que ponto vale "complicar para facilitar".

## GIFs & Screenshots

* ![imagem referência](https://cdn-std.droplr.net/files/acc_114520/530pu4)

2021-08-19 13:58 UTC, rdgborges requested changes
Boa Dairan! O componente tá com a estrutura bem feita. Fiz alguns comentários para tentar deixarmos ele no mesmo padrão dos outros componentes que tão sendo desenvolvidos.

2021-08-19 13:58 UTC, rdgborges commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +  private func configureUI() {
O que acha de mantermos o mesmo padrão de nomenclatura das outras Views, trocando o nome desse método para `configureSubviews`

2021-08-19 13:58 UTC, rdgborges commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +  convenience init(withName image: String) {
É um ótimo uso do `convenience init`. 👏  Para seguir o padrão das outras views, podemos criar um CircularImageViewModel, que tem uma UIImage, e passar esse view model por um método configure(with viewModel: CircularImageViewModel) aqui na classe. O que acha?

2021-08-19 13:58 UTC, rdgborges commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +    super.init(frame: .zero)
Aqui faltou chamar os métodos de configuração da View.

2021-08-19 13:58 UTC, rdgborges commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +    let imagemView = UIImageView()
Corrigir o nome para `imageView`

2021-08-19 17:17 UTC, dairan commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +    super.init(frame: .zero)
Eu não consegui entender. 

O [self.init()](https://github.com/dairan/hereminders-ios/blob/00daee1e240d89f5619622ed4b1edced2b2fd8bf/Hereminders/Scenes/Components/Views/CircularImageView.swift#L21)  não era para chamar o [override Init()](https://github.com/dairan/hereminders-ios/blob/00daee1e240d89f5619622ed4b1edced2b2fd8bf/Hereminders/Scenes/Components/Views/CircularImageView.swift#L15), que por sua vez, chamaria os métodos configureSubviews() e configureConstrains()?

2021-08-20 17:47 UTC, rdgborges commented on Hereminders/Scenes/Components/Views/CircularImageView.swift
> +    super.init(frame: .zero)
Vi agora que os métodos de configuração tão lá.

Só um outro ponto: você não precisa fazer um `override init(frame: CGRect)`. Só precisa criar um novo init mesmo:

```
init() {
    super.init(frame: .zero)
    configureSubviews()
    configureConstrains()
}

2021-08-20 20:38 UTC, rdgborges approved these changes

2021-08-23 13:41 UTC, merged