Implementação RemindeListView usando ViewCode e seus respectivos testes
devpass-tech/hereminders-ios pull request #27
Opened 2021-08-29 20:01 UTC by dairan

## What does this PR do

* Implementação RemindeListView usando ViewCode e seus respectivos testes

## TODOs

* Aparece no log que está com erros de constraints 

## GIFs & Screenshots

* ![Imagem de referência](https://github.com/dairan/hereminders-ios/blob/f3aadab6aeae96887030d4dbd9d61e0c972547b5/HeremindersTests/SnapshotTests/__Snapshots__/ReminderListViewViewCodeTests/testReminderListViewViewCode.1.png?raw=true)

2021-08-30 14:31 UTC, gsillis commented
@rdgborges estava vendo q no app em produção a cell com a lista de reminder é igual a essa, acho que ficaria melhor se o footer da tableview fosse uma uiview e cell acompanhasse a margem dos outros elementos.

2021-08-30 23:23 UTC, rdgborges requested changes

2021-08-30 23:23 UTC, rdgborges commented on Hereminders/Scenes/Home/ReminderListView/Views/ReminderListViewController.swift
> +class ReminderListViewController: UIViewController {
Nesse caso, a ReminderListView vai ser utilizada apenas como um subcomponente de um ViewController, e não como a View inteira de uma VC. Então acredito que possa remover esse arquivo do projeto.

2021-08-30 23:23 UTC, rdgborges commented on Hereminders/Scenes/Home/ReminderListView/Views/ReminderListViewViewCode.swift
> +struct LembreteVM {
Struct não mais utilizado. Pode remover.

2021-08-30 23:23 UTC, rdgborges commented on Hereminders/Scenes/Home/ReminderListView/Views/ReminderListViewViewCode.swift
> +    stackView.directionalLayoutMargins = NSDirectionalEdgeInsets(top: marginEdge,
Uma estratégia que você pode usar para colocar margens em somente um componente é criar uma "container view", adicionar o componente e adicionar constraints de margens específicas para ele. Ex:

```

private var titleSubtitleContainerView: UIView = {
  let view = UIVIew()
  view..translatesAutoresizingMaskIntoConstraints = false
  return view
}()

//...

self.titleSubtitleContainerView.addSubview(self.titleSubtitle)
self.stackView.addArrangedSubview(self.titleSubtitleContainerView)

//...

titleSubtitle.topAnchor.constraint(equalTo: titleSubtitleContainerView.topAnchor, constant: 16)),
titleSubtitle.leadingAnchor.constraint(equalTo: titleSubtitleContainerView.leadingAnchor, constant: 16)),
titleSubtitle.trailingAnchor.constraint(equalTo: titleSubtitleContainerView.trailingAnchor, constant: -16)),
titleSubtitle.bottomAnchor.constraint(equalTo: titleSubtitleContainerView.bottomAnchor, constant: -16)),
```

2021-08-30 23:23 UTC, rdgborges commented on Hereminders/Scenes/Home/ReminderListView/Views/ReminderListViewViewCode.swift
> +//    viewModel.reminders.count
Remover linha comentada.

2021-08-31 19:17 UTC, rdgborges requested changes
Boa Dairan! Vc conseguiu acertar as margens do TitleSubtitleView!

Agora é necessário consertar também para o DividerView (leading = 16, trailing = -16) e ButtonView (mesmo formato da TitleSubtitleView).

2021-09-02 16:57 UTC, rdgborges requested changes

2021-09-02 16:57 UTC, rdgborges commented on Hereminders/Scenes/Home/ReminderListView/Views/ReminderListViewViewCode.swift
> +    cell.textLabel?.text = lembrete.description
É preciso configurar a célula também com o "evento" que vai enviar o lembrete. Dica:

`cell?.detailTextLabel?.text = lembrete.event == 0 ? L10n.Reminderlist.onEntry : L10n.Reminderlist.onExit`

event == 0 -> Lembrete é enviado quando a pessoa entrar na área do local
event == 1 -> Quando a pessoa sair.

2021-09-09 16:51 UTC, rdgborges approved these changes

2021-09-09 16:58 UTC, merged