Implemented PlaceTableViewCell and Snapshot Test for this component
devpass-tech/hereminders-ios pull request #43
Opened 2021-09-23 15:37 UTC by allanpereir

## What does this PR do

* Implemented a new Table View Cell component and Snapshot Test for this component

## TODOs

* N/A

## How should this be manually tested

* N/A

## Any background context you want to provide

* N/A

## GIFs & Screenshots

![testPlaceTableViewCell 1](https://user-images.githubusercontent.com/58039168/134538099-90f28d3a-af41-4561-859f-2d4bc41ad575.png)

2021-09-23 19:52 UTC, rdgborges requested changes

2021-09-23 19:52 UTC, rdgborges commented on Hereminders/Scenes/Components/PlaceTableViewCell/PlaceTableViewCell.swift
> +        dividerView.backgroundColor = .red
Remover essa linha por que a DividerView já seta sua própria cor.

2021-09-23 19:52 UTC, rdgborges commented on Hereminders/Scenes/Components/PlaceTableViewCell/PlaceTableViewCell.swift
> +        self.accessoryType = .disclosureIndicator
Como essa é uma configuração padrão desse componente, ela não precisa ser setada somente quando o método configure for chamado.

Recomendo você fazer essa chamada no método `init`, assim sempre essa célula terá o disclosure indicator, desde a sua inicialização.

2021-09-23 20:55 UTC, allanpereir commented on Hereminders/Scenes/Components/PlaceTableViewCell/PlaceTableViewCell.swift
> +        dividerView.backgroundColor = .red
Removido a linha que seta a cor do dividerView conforme mencionado.

2021-09-23 20:56 UTC, allanpereir commented on Hereminders/Scenes/Components/PlaceTableViewCell/PlaceTableViewCell.swift
> +        self.accessoryType = .disclosureIndicator
Incluído o disclosure indicator no método init.

2021-09-24 15:29 UTC, rdgborges approved these changes

2021-09-24 15:29 UTC, merged