Place details view
devpass-tech/hereminders-ios pull request #49
Opened 2021-09-29 21:19 UTC by elenadiniz

## What does this PR do

- Finalizada a implementação do Layout utilizando ViewCode.
- Atualização dos locais sendo feita através do método configure da PlaceDetailsView para a PlaceDetailsViewController.
- Utilização do ViewModel para concluir a atualização do conteúdo.
- Exclusão da célula XIB, usada para layout da tela antes da refatoração.
- Usada extension Protocol para avisar a ViewController sempre que os dados vindos da DataController, precisarem ser atualizados.

## TODOs

* N/A

## How should this be manually tested

1. Normal usage.
2. Managing the saved places.
3. Saving new places.

## Any background context you want to provide

* N/A

## GIFs & Screenshots

* ![description](https://upload.wikimedia.org/wikipedia/commons/7/73/Roflcopter.gif)

2021-09-29 21:44 UTC, rdgborges requested changes
Parabéns pelo seu primeiro PR na Devpass, @elenadiniz! 🎉🎉🎉

2021-09-29 21:44 UTC, rdgborges commented on Hereminders/Scenes/PlaceDetails/PlaceDetailsViewController.swift
> +        let viewModelMap = MapLocationViewModel(coordinate: self.place.coordinate, title: self.place.name)
O que acha de mover esse código para dentro do método `configure` da `PlaceDetailsView`?

Assim só precisamos chamar o método `getDetails()` e remover o `configureMapLocationView`.

2021-09-29 22:57 UTC, elenadiniz commented on Hereminders/Scenes/PlaceDetails/PlaceDetailsViewController.swift
> +        let viewModelMap = MapLocationViewModel(coordinate: self.place.coordinate, title: self.place.name)
Done ✅

2021-09-30 13:20 UTC, brudrago commented on Hereminders/Scenes/PlaceDetails/PlaceDetailsView.swift
> +import UIKit
Aqui só precisa fazer um import , o UIKit já contém o Foundation

2021-09-30 13:36 UTC, brudrago commented on Hereminders/Scenes/PlaceDetails/PlaceDetailsView.swift
> +
No projeto tem um protocolo chamado ViewProtocol , que implementa essas funções de add objetos,constraints, acredito que seria legal utilizar para padronizar as novas implementações de view utilizando o ViewCode. Neste caso , ao invés de funções privados você utilizaria as funcs do protocol.

2021-10-01 18:09 UTC, elenadiniz commented on Hereminders/Scenes/PlaceDetails/PlaceDetailsView.swift
> +
Done ✅ Valeu pelas dicas Bru!

2021-10-04 17:43 UTC, rdgborges approved these changes

2021-10-04 17:45 UTC, merged